### PR TITLE
Watersmart 498

### PR DESCRIPTION
**Pull request by mbucknell**

### CODE REVIEW

**Comment by mbucknell** [comment]
The inset map now works correctly and adding the calculating stats portion of the page. Still to do is the plotting portion of the page.

**Comment by mamcderm-usgs** [comment]
looks good :+1:

**Comment by mbucknell** [comment]
Looks like I didn't merge from before ... my bad. The new code added handles plotting the streamflow data which should be very similar to the water budget huc data page view.

**Comment by mbucknell** [comment]
@mamcderm-usgs, could you please review when you have a chance.

**Comment by mamcderm-usgs** [comment]
Looks good :+1:

**Pull request merged**
